### ISSUE TITLE
Issue loading rubygems  in Ruby >= 2.5

### ISSUE THREAD

**Issue by icostan** [ruby-test-mode/ruby-test-mode#51]
When executing "run-test-run-at-point" function it adds "-rubygems" argument and the entire command fails because 'ubygems.rb' was removed in Ruby 2.5 (see rubygems/rubygems#2393)

```sh
Traceback (most recent call last):
	1: from /Users/syca/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/syca/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- ubygems (LoadError)
```

I can easily fix this issue (and a few open ones) but it looks like this project is no longer maintained.

@r0man are there any plans going forward?  is anyone actively maintaining it?

If you need some help I can take care of your repo and merge PRs and everything, or I can fork it and continue working on my own repo, either way is fine with me. 

Cheers.

**Comment by r0man** [comment]
Hi @icostan,

I'm not using Ruby myself these days. If you have a fix for this issue I'm happy to merge a PR. Regarding the transfer of ownership, I'm interested what @febeling has to say about this. A lot of the code came from him, and I think he is still involved in Ruby and has commit access to this repo.

@febeling Hi!, and what do you think?

**Comment by febeling** [comment]
Thought about it. How about graduating the repo into a org? That's often nice when people originally involved with a package step back, and users become contributors or maintainers, less personal, and more standing on its own. What do you think?

Also, sorry for the late response.

**Comment by r0man** [comment]
@febeling Sounds good to me, I moved the the repository into the org and opend a PR on melpa to update the recipe.

https://github.com/melpa/melpa/pull/6046

**Comment by febeling** [comment]
Cool, thanks @r0man 

So the new permanent home is [ruby-test-mode/ruby-test-mode](https://github.com/ruby-test-mode/ruby-test-mode). Happy to give you commit on first PR @icostan.

**Comment by icostan** [comment]
Yes, the org approach is the best, thank you @r0man  @febeling.  Going to dig into other issues as well.

**Comment by icostan** [comment]
Alright, I rebased my repo on top of your latest changes and here is the new PR #52 for this issue and one more #53 to fix Travis URL and emacs versions. 

@febeling  please do your magic.
